# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: devops-core
    goos:
      - linux
      # - windows
      # - darwin
  - id: devops-kubernetes-plugin
    main: ./plugin
    binary: kubernetes
    goos:
      - linux
      # - windows
      # - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

blobs:
  - provider: gs
    bucket: devops-cli-artifacts
    folder: "releases/devops/{{.Version}}"
