before:
  hooks:
    - go mod tidy
builds:
  - id: devops-core
    flags:
      - -tags=release
    main: ./cmd/devops
    binary: devops
    goos:
      - linux
      # - windows
      - darwin
release:
  disable: true
  skip_upload: true

archives:
  - builds:
      - devops-core
    id: devops-core
    replacements:
      # darwin: Darwin
      # linux: Linux
      # windows: Windows
      386: i386
      amd64: x86_64
    files:
      - ./cmd/devops/config.yaml
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

blobs:
  - provider: gs
    bucket: devops-cli-artifacts
    folder: "releases/devops/{{.Version}}"
    ids:
      - devops-core
    extra_files:
      - glob: ./install.sh
      - glob: devops-frontend/ui.tar.gz
