before:
  hooks:
    - go mod tidy
builds:
  - id: devops-core
    flags:
    - -tags=release
    main: ./cmd/devops
    goos:
      - linux
      # - windows
      - darwin
  - id: devops-kubernetes-plugin
    flags:
    - -tags=release
    - -o kubernetes
    main: ./plugin/kubernetes
    binary: kubernetes
    goos:
      - linux
      # - windows
      - darwin
release:
  disable: true
  skip_upload: true

archives:
  - builds:
    - devops-core
    id: devops-core
    replacements:
      # darwin: Darwin
      # linux: Linux
      # windows: Windows
      386: i386
      amd64: x86_64
    files:
      - src: ./cmd/devops/config.yaml
        dst: config.yaml
        strip_parent: true
  - builds:
    - devops-kubernetes-plugin
    id: devops-kubernetes-plugin
    name_template: "devops-kubernetes-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: plugin/kubernetes/resource_config
        dst: resource_config
        strip_parent: true
      - src: plugin/kubernetes/config.yaml
        dst: config.yaml
        strip_parent: true
    replacements:
      # darwin: Darwin
      # linux: Linux
      # windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

blobs:
  - provider: gs
    bucket: devops-cli-artifacts
    folder: "releases/devops/{{.Version}}"
    ids:
    - devops-core
    - devops-kubernetes-plugin
    extra_files:
    - glob: ./install.sh
