/* tslint:disable */
/* eslint-disable */
/**
 * NEW Devops API
 * Devops API Sec
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelServer
 */
export interface ModelServer {
    /**
     * 
     * @type {string}
     * @memberof ModelServer
     */
    address: string;
}

/**
 * Check if a given object implements the ModelServer interface.
 */
export function instanceOfModelServer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function ModelServerFromJSON(json: any): ModelServer {
    return ModelServerFromJSONTyped(json, false);
}

export function ModelServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelServer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
    };
}

export function ModelServerToJSON(value?: ModelServer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
    };
}

