/* tslint:disable */
/* eslint-disable */
/**
 * NEW Devops API
 * Devops API Sec
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelEventResponse
 */
export interface ModelEventResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelEventResponse
     */
    id?: string;
    /**
     * 
     * @type {object}
     * @memberof ModelEventResponse
     */
    result?: object;
}

/**
 * Check if a given object implements the ModelEventResponse interface.
 */
export function instanceOfModelEventResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelEventResponseFromJSON(json: any): ModelEventResponse {
    return ModelEventResponseFromJSONTyped(json, false);
}

export function ModelEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelEventResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ModelEventResponseToJSON(value?: ModelEventResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'result': value.result,
    };
}

