/* tslint:disable */
/* eslint-disable */
/**
 * NEW Devops API
 * Devops API Sec
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProtoServerInput
 */
export interface ProtoServerInput {
    /**
     * 
     * @type {boolean}
     * @memberof ProtoServerInput
     */
    required?: boolean;
}

/**
 * Check if a given object implements the ProtoServerInput interface.
 */
export function instanceOfProtoServerInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProtoServerInputFromJSON(json: any): ProtoServerInput {
    return ProtoServerInputFromJSONTyped(json, false);
}

export function ProtoServerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtoServerInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'required': !exists(json, 'required') ? undefined : json['required'],
    };
}

export function ProtoServerInputToJSON(value?: ProtoServerInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'required': value.required,
    };
}

