/* tslint:disable */
/* eslint-disable */
/**
 * NEW Devops API
 * Devops API Sec
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructpbValue
 */
export interface StructpbValue {
    /**
     * The kind of value.
     * 
     * Types that are assignable to Kind:
     * 	*Value_NullValue
     * 	*Value_NumberValue
     * 	*Value_StringValue
     * 	*Value_BoolValue
     * 	*Value_StructValue
     * 	*Value_ListValue
     * @type {object}
     * @memberof StructpbValue
     */
    kind?: object;
}

/**
 * Check if a given object implements the StructpbValue interface.
 */
export function instanceOfStructpbValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructpbValueFromJSON(json: any): StructpbValue {
    return StructpbValueFromJSONTyped(json, false);
}

export function StructpbValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructpbValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
    };
}

export function StructpbValueToJSON(value?: StructpbValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
    };
}

